<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.9" tiledversion="1.9.0" name="dungeon" tilewidth="16" tileheight="16" tilecount="380" columns="20">
 <image source="tiles_dungeon.png" width="320" height="304"/>
 <tile id="0" class="ground"/>
 <tile id="1" class="ground"/>
 <tile id="2" class="ground"/>
 <tile id="4" class="ground"/>
 <tile id="5" class="ground"/>
 <tile id="6" class="ground"/>
 <tile id="7" class="ground"/>
 <tile id="8" class="ground"/>
 <tile id="9" class="ground"/>
 <tile id="10" class="ground"/>
 <tile id="11" class="ground"/>
 <tile id="12" class="ground"/>
 <tile id="13" class="ground"/>
 <tile id="20" class="ground"/>
 <tile id="21" class="ground"/>
 <tile id="22" class="ground"/>
 <tile id="23" class="ground"/>
 <tile id="24" class="ground"/>
 <tile id="25" class="ground"/>
 <tile id="26" class="ground"/>
 <tile id="27" class="ground"/>
 <tile id="28" class="ground"/>
 <tile id="29" class="ground"/>
 <tile id="30" class="ground"/>
 <tile id="31" class="ground"/>
 <tile id="32" class="ground"/>
 <tile id="33" class="ground"/>
 <tile id="40" class="ground"/>
 <tile id="41" class="ground"/>
 <tile id="42" class="ground"/>
 <tile id="43" class="ground"/>
 <tile id="44" class="ground"/>
 <tile id="45" class="ground"/>
 <tile id="46" class="ground"/>
 <tile id="47" class="ground"/>
 <tile id="48" class="ground"/>
 <tile id="49" class="ground"/>
 <tile id="50" class="ground"/>
 <tile id="51" class="ground"/>
 <tile id="67" class="ground"/>
 <tile id="68" class="ground"/>
 <tile id="334" class="chest"/>
</tileset>
